{"name": "test_create_already_created_user_error", "status": "passed", "start": 1736196506739, "stop": 1736196506976, "uuid": "0817a7bb-77bf-43d8-9c00-93c81725513e", "historyId": "a4681bbd45e4d458c578142f1f9ec1af", "testCaseId": "a4681bbd45e4d458c578142f1f9ec1af", "fullName": "tests.test_user_create.TestCreateUser#test_create_already_created_user_error", "labels": [{"name": "story", "value": "Попытка создания уже зарегистрированного пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_create"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "Oxanas-MacBook-Pro.local"}, {"name": "thread", "value": "90867-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_create"}]}